apiVersion: apps/v1
kind: Deployment
metadata:
  name: numrecd-noise
  labels:
    app: numrecd-noise
spec:
  selector:
    matchLabels:
      app: numrecd-noise
  replicas: 1
  template:
    metadata:
      labels:
        app: numrecd-noise
    spec:
      containers:
      - name: numrecd-noise
        image: registry.cn-beijing.aliyuncs.com/zhengsj/hongbao:numrecd
        imagePullPolicy: IfNotPresent
#        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #   failureThreshold: 1
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 1
          periodSeconds: 2
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 1
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

---

apiVersion: v1
kind: Service
metadata:
  name: numrecd-noise
  labels:
    app: numrecd-noise
spec:
  selector:
    app: numrecd-noise
  ports:
  - nodePort: 32200
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: numrecd-noise
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: numrecd-noise
  minReplicas: 1
  maxReplicas: 1000
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1000
        periodSeconds: 1
#      - type: Percent
#        value: 900
#        periodSeconds: 1
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1000
        periodSeconds: 1
#  behavior:
#   scaleDown:
#     stabilizationWindowSeconds: 300
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#   scaleUp:
#     stabilizationWindowSeconds: 0
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#     - type: Pods
#       value: 4
#       periodSeconds: 15
#     selectPolicy: Max

