YAML_FILEPATH=configs/k8s/numrecd.yml
sed "s/APP_NAME/numrecd$TOTAL/g" configs/k8s/numrecd-detail.yaml.template > $YAML_FILEPATH
sed -i '' "s/CPU_REQUEST/$CPU_REQUEST/g" $YAML_FILEPATH
sed -i '' "s/CPU_LIMIT/$CPU_LIMIT/g" $YAML_FILEPATH
sed -i '' "s/CPU_SCALE_THRESHOLD/$CPU_SCALE_THRESHOLD/g" $YAML_FILEPATH
sed -i '' "s/CPU_SCALE_UP_LIMIT/$CPU_SCALE_UP_LIMIT/g" $YAML_FILEPATH
sed -i '' "s/INIT_REPLICA_NUM/$INIT_REPLICA_NUM/g" $YAML_FILEPATH
sed -i '' "s/MAX_REPLICA_NUM/$MAX_REPLICA_NUM/g" $YAML_FILEPATH